// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shm_messages.proto

#include "shm_messages.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace shm_ipc {
PROTOBUF_CONSTEXPR HeartbeatProto::HeartbeatProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.client_id_)*/0
  , /*decltype(_impl_.seq_)*/0
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeartbeatProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatProtoDefaultTypeInternal() {}
  union {
    HeartbeatProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatProtoDefaultTypeInternal _HeartbeatProto_default_instance_;
PROTOBUF_CONSTEXPR ClientMsgProto::ClientMsgProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.seq_)*/0
  , /*decltype(_impl_.tick_)*/0
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ClientMsgProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientMsgProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientMsgProtoDefaultTypeInternal() {}
  union {
    ClientMsgProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientMsgProtoDefaultTypeInternal _ClientMsgProto_default_instance_;
}  // namespace shm_ipc
static ::_pb::Metadata file_level_metadata_shm_5fmessages_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_shm_5fmessages_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_shm_5fmessages_2eproto = nullptr;

const uint32_t TableStruct_shm_5fmessages_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::shm_ipc::HeartbeatProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::shm_ipc::HeartbeatProto, _impl_.client_id_),
  PROTOBUF_FIELD_OFFSET(::shm_ipc::HeartbeatProto, _impl_.seq_),
  PROTOBUF_FIELD_OFFSET(::shm_ipc::HeartbeatProto, _impl_.timestamp_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::shm_ipc::ClientMsgProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::shm_ipc::ClientMsgProto, _impl_.seq_),
  PROTOBUF_FIELD_OFFSET(::shm_ipc::ClientMsgProto, _impl_.tick_),
  PROTOBUF_FIELD_OFFSET(::shm_ipc::ClientMsgProto, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::shm_ipc::ClientMsgProto, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::shm_ipc::HeartbeatProto)},
  { 9, -1, -1, sizeof(::shm_ipc::ClientMsgProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::shm_ipc::_HeartbeatProto_default_instance_._instance,
  &::shm_ipc::_ClientMsgProto_default_instance_._instance,
};

const char descriptor_table_protodef_shm_5fmessages_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022shm_messages.proto\022\007shm_ipc\"C\n\016Heartbe"
  "atProto\022\021\n\tclient_id\030\001 \001(\005\022\013\n\003seq\030\002 \001(\005\022"
  "\021\n\ttimestamp\030\003 \001(\003\"O\n\016ClientMsgProto\022\013\n\003"
  "seq\030\001 \001(\005\022\014\n\004tick\030\002 \001(\005\022\021\n\ttimestamp\030\003 \001"
  "(\003\022\017\n\007payload\030\004 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_shm_5fmessages_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_shm_5fmessages_2eproto = {
    false, false, 187, descriptor_table_protodef_shm_5fmessages_2eproto,
    "shm_messages.proto",
    &descriptor_table_shm_5fmessages_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_shm_5fmessages_2eproto::offsets,
    file_level_metadata_shm_5fmessages_2eproto, file_level_enum_descriptors_shm_5fmessages_2eproto,
    file_level_service_descriptors_shm_5fmessages_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_shm_5fmessages_2eproto_getter() {
  return &descriptor_table_shm_5fmessages_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_shm_5fmessages_2eproto(&descriptor_table_shm_5fmessages_2eproto);
namespace shm_ipc {

// ===================================================================

class HeartbeatProto::_Internal {
 public:
};

HeartbeatProto::HeartbeatProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:shm_ipc.HeartbeatProto)
}
HeartbeatProto::HeartbeatProto(const HeartbeatProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HeartbeatProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){}
    , decltype(_impl_.seq_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.client_id_, &from._impl_.client_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.client_id_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:shm_ipc.HeartbeatProto)
}

inline void HeartbeatProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.client_id_){0}
    , decltype(_impl_.seq_){0}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HeartbeatProto::~HeartbeatProto() {
  // @@protoc_insertion_point(destructor:shm_ipc.HeartbeatProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HeartbeatProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HeartbeatProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HeartbeatProto::Clear() {
// @@protoc_insertion_point(message_clear_start:shm_ipc.HeartbeatProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.client_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.client_id_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeartbeatProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 client_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.client_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 seq = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HeartbeatProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shm_ipc.HeartbeatProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 client_id = 1;
  if (this->_internal_client_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_client_id(), target);
  }

  // int32 seq = 2;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_seq(), target);
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shm_ipc.HeartbeatProto)
  return target;
}

size_t HeartbeatProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shm_ipc.HeartbeatProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 client_id = 1;
  if (this->_internal_client_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_client_id());
  }

  // int32 seq = 2;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_seq());
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartbeatProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HeartbeatProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartbeatProto::GetClassData() const { return &_class_data_; }


void HeartbeatProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HeartbeatProto*>(&to_msg);
  auto& from = static_cast<const HeartbeatProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:shm_ipc.HeartbeatProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_client_id() != 0) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  if (from._internal_seq() != 0) {
    _this->_internal_set_seq(from._internal_seq());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HeartbeatProto::CopyFrom(const HeartbeatProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shm_ipc.HeartbeatProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartbeatProto::IsInitialized() const {
  return true;
}

void HeartbeatProto::InternalSwap(HeartbeatProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HeartbeatProto, _impl_.timestamp_)
      + sizeof(HeartbeatProto::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(HeartbeatProto, _impl_.client_id_)>(
          reinterpret_cast<char*>(&_impl_.client_id_),
          reinterpret_cast<char*>(&other->_impl_.client_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HeartbeatProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shm_5fmessages_2eproto_getter, &descriptor_table_shm_5fmessages_2eproto_once,
      file_level_metadata_shm_5fmessages_2eproto[0]);
}

// ===================================================================

class ClientMsgProto::_Internal {
 public:
};

ClientMsgProto::ClientMsgProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:shm_ipc.ClientMsgProto)
}
ClientMsgProto::ClientMsgProto(const ClientMsgProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ClientMsgProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , decltype(_impl_.seq_){}
    , decltype(_impl_.tick_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_payload().empty()) {
    _this->_impl_.payload_.Set(from._internal_payload(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.seq_, &from._impl_.seq_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:shm_ipc.ClientMsgProto)
}

inline void ClientMsgProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.payload_){}
    , decltype(_impl_.seq_){0}
    , decltype(_impl_.tick_){0}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ClientMsgProto::~ClientMsgProto() {
  // @@protoc_insertion_point(destructor:shm_ipc.ClientMsgProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ClientMsgProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.payload_.Destroy();
}

void ClientMsgProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ClientMsgProto::Clear() {
// @@protoc_insertion_point(message_clear_start:shm_ipc.ClientMsgProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.payload_.ClearToEmpty();
  ::memset(&_impl_.seq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.seq_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ClientMsgProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 seq = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.seq_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 tick = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tick_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes payload = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ClientMsgProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:shm_ipc.ClientMsgProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 seq = 1;
  if (this->_internal_seq() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_seq(), target);
  }

  // int32 tick = 2;
  if (this->_internal_tick() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_tick(), target);
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_timestamp(), target);
  }

  // bytes payload = 4;
  if (!this->_internal_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_payload(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:shm_ipc.ClientMsgProto)
  return target;
}

size_t ClientMsgProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:shm_ipc.ClientMsgProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes payload = 4;
  if (!this->_internal_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_payload());
  }

  // int32 seq = 1;
  if (this->_internal_seq() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_seq());
  }

  // int32 tick = 2;
  if (this->_internal_tick() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tick());
  }

  // int64 timestamp = 3;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ClientMsgProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ClientMsgProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ClientMsgProto::GetClassData() const { return &_class_data_; }


void ClientMsgProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ClientMsgProto*>(&to_msg);
  auto& from = static_cast<const ClientMsgProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:shm_ipc.ClientMsgProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (from._internal_seq() != 0) {
    _this->_internal_set_seq(from._internal_seq());
  }
  if (from._internal_tick() != 0) {
    _this->_internal_set_tick(from._internal_tick());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ClientMsgProto::CopyFrom(const ClientMsgProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:shm_ipc.ClientMsgProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientMsgProto::IsInitialized() const {
  return true;
}

void ClientMsgProto::InternalSwap(ClientMsgProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.payload_, lhs_arena,
      &other->_impl_.payload_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClientMsgProto, _impl_.timestamp_)
      + sizeof(ClientMsgProto::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(ClientMsgProto, _impl_.seq_)>(
          reinterpret_cast<char*>(&_impl_.seq_),
          reinterpret_cast<char*>(&other->_impl_.seq_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ClientMsgProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shm_5fmessages_2eproto_getter, &descriptor_table_shm_5fmessages_2eproto_once,
      file_level_metadata_shm_5fmessages_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace shm_ipc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::shm_ipc::HeartbeatProto*
Arena::CreateMaybeMessage< ::shm_ipc::HeartbeatProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::shm_ipc::HeartbeatProto >(arena);
}
template<> PROTOBUF_NOINLINE ::shm_ipc::ClientMsgProto*
Arena::CreateMaybeMessage< ::shm_ipc::ClientMsgProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::shm_ipc::ClientMsgProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
