// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shm_messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_shm_5fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_shm_5fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_shm_5fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_shm_5fmessages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_shm_5fmessages_2eproto;
namespace shm_ipc {
class ClientMsgProto;
struct ClientMsgProtoDefaultTypeInternal;
extern ClientMsgProtoDefaultTypeInternal _ClientMsgProto_default_instance_;
class HeartbeatProto;
struct HeartbeatProtoDefaultTypeInternal;
extern HeartbeatProtoDefaultTypeInternal _HeartbeatProto_default_instance_;
}  // namespace shm_ipc
PROTOBUF_NAMESPACE_OPEN
template<> ::shm_ipc::ClientMsgProto* Arena::CreateMaybeMessage<::shm_ipc::ClientMsgProto>(Arena*);
template<> ::shm_ipc::HeartbeatProto* Arena::CreateMaybeMessage<::shm_ipc::HeartbeatProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace shm_ipc {

// ===================================================================

class HeartbeatProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:shm_ipc.HeartbeatProto) */ {
 public:
  inline HeartbeatProto() : HeartbeatProto(nullptr) {}
  ~HeartbeatProto() override;
  explicit PROTOBUF_CONSTEXPR HeartbeatProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartbeatProto(const HeartbeatProto& from);
  HeartbeatProto(HeartbeatProto&& from) noexcept
    : HeartbeatProto() {
    *this = ::std::move(from);
  }

  inline HeartbeatProto& operator=(const HeartbeatProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartbeatProto& operator=(HeartbeatProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartbeatProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartbeatProto* internal_default_instance() {
    return reinterpret_cast<const HeartbeatProto*>(
               &_HeartbeatProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HeartbeatProto& a, HeartbeatProto& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartbeatProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartbeatProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartbeatProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartbeatProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartbeatProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartbeatProto& from) {
    HeartbeatProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartbeatProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "shm_ipc.HeartbeatProto";
  }
  protected:
  explicit HeartbeatProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kSeqFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // int32 client_id = 1;
  void clear_client_id();
  int32_t client_id() const;
  void set_client_id(int32_t value);
  private:
  int32_t _internal_client_id() const;
  void _internal_set_client_id(int32_t value);
  public:

  // int32 seq = 2;
  void clear_seq();
  int32_t seq() const;
  void set_seq(int32_t value);
  private:
  int32_t _internal_seq() const;
  void _internal_set_seq(int32_t value);
  public:

  // int64 timestamp = 3;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:shm_ipc.HeartbeatProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t client_id_;
    int32_t seq_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shm_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class ClientMsgProto final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:shm_ipc.ClientMsgProto) */ {
 public:
  inline ClientMsgProto() : ClientMsgProto(nullptr) {}
  ~ClientMsgProto() override;
  explicit PROTOBUF_CONSTEXPR ClientMsgProto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientMsgProto(const ClientMsgProto& from);
  ClientMsgProto(ClientMsgProto&& from) noexcept
    : ClientMsgProto() {
    *this = ::std::move(from);
  }

  inline ClientMsgProto& operator=(const ClientMsgProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientMsgProto& operator=(ClientMsgProto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientMsgProto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientMsgProto* internal_default_instance() {
    return reinterpret_cast<const ClientMsgProto*>(
               &_ClientMsgProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ClientMsgProto& a, ClientMsgProto& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientMsgProto* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientMsgProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientMsgProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientMsgProto>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientMsgProto& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientMsgProto& from) {
    ClientMsgProto::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientMsgProto* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "shm_ipc.ClientMsgProto";
  }
  protected:
  explicit ClientMsgProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 4,
    kSeqFieldNumber = 1,
    kTickFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // bytes payload = 4;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // int32 seq = 1;
  void clear_seq();
  int32_t seq() const;
  void set_seq(int32_t value);
  private:
  int32_t _internal_seq() const;
  void _internal_set_seq(int32_t value);
  public:

  // int32 tick = 2;
  void clear_tick();
  int32_t tick() const;
  void set_tick(int32_t value);
  private:
  int32_t _internal_tick() const;
  void _internal_set_tick(int32_t value);
  public:

  // int64 timestamp = 3;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:shm_ipc.ClientMsgProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    int32_t seq_;
    int32_t tick_;
    int64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shm_5fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HeartbeatProto

// int32 client_id = 1;
inline void HeartbeatProto::clear_client_id() {
  _impl_.client_id_ = 0;
}
inline int32_t HeartbeatProto::_internal_client_id() const {
  return _impl_.client_id_;
}
inline int32_t HeartbeatProto::client_id() const {
  // @@protoc_insertion_point(field_get:shm_ipc.HeartbeatProto.client_id)
  return _internal_client_id();
}
inline void HeartbeatProto::_internal_set_client_id(int32_t value) {
  
  _impl_.client_id_ = value;
}
inline void HeartbeatProto::set_client_id(int32_t value) {
  _internal_set_client_id(value);
  // @@protoc_insertion_point(field_set:shm_ipc.HeartbeatProto.client_id)
}

// int32 seq = 2;
inline void HeartbeatProto::clear_seq() {
  _impl_.seq_ = 0;
}
inline int32_t HeartbeatProto::_internal_seq() const {
  return _impl_.seq_;
}
inline int32_t HeartbeatProto::seq() const {
  // @@protoc_insertion_point(field_get:shm_ipc.HeartbeatProto.seq)
  return _internal_seq();
}
inline void HeartbeatProto::_internal_set_seq(int32_t value) {
  
  _impl_.seq_ = value;
}
inline void HeartbeatProto::set_seq(int32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:shm_ipc.HeartbeatProto.seq)
}

// int64 timestamp = 3;
inline void HeartbeatProto::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t HeartbeatProto::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t HeartbeatProto::timestamp() const {
  // @@protoc_insertion_point(field_get:shm_ipc.HeartbeatProto.timestamp)
  return _internal_timestamp();
}
inline void HeartbeatProto::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void HeartbeatProto::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:shm_ipc.HeartbeatProto.timestamp)
}

// -------------------------------------------------------------------

// ClientMsgProto

// int32 seq = 1;
inline void ClientMsgProto::clear_seq() {
  _impl_.seq_ = 0;
}
inline int32_t ClientMsgProto::_internal_seq() const {
  return _impl_.seq_;
}
inline int32_t ClientMsgProto::seq() const {
  // @@protoc_insertion_point(field_get:shm_ipc.ClientMsgProto.seq)
  return _internal_seq();
}
inline void ClientMsgProto::_internal_set_seq(int32_t value) {
  
  _impl_.seq_ = value;
}
inline void ClientMsgProto::set_seq(int32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:shm_ipc.ClientMsgProto.seq)
}

// int32 tick = 2;
inline void ClientMsgProto::clear_tick() {
  _impl_.tick_ = 0;
}
inline int32_t ClientMsgProto::_internal_tick() const {
  return _impl_.tick_;
}
inline int32_t ClientMsgProto::tick() const {
  // @@protoc_insertion_point(field_get:shm_ipc.ClientMsgProto.tick)
  return _internal_tick();
}
inline void ClientMsgProto::_internal_set_tick(int32_t value) {
  
  _impl_.tick_ = value;
}
inline void ClientMsgProto::set_tick(int32_t value) {
  _internal_set_tick(value);
  // @@protoc_insertion_point(field_set:shm_ipc.ClientMsgProto.tick)
}

// int64 timestamp = 3;
inline void ClientMsgProto::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t ClientMsgProto::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t ClientMsgProto::timestamp() const {
  // @@protoc_insertion_point(field_get:shm_ipc.ClientMsgProto.timestamp)
  return _internal_timestamp();
}
inline void ClientMsgProto::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void ClientMsgProto::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:shm_ipc.ClientMsgProto.timestamp)
}

// bytes payload = 4;
inline void ClientMsgProto::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& ClientMsgProto::payload() const {
  // @@protoc_insertion_point(field_get:shm_ipc.ClientMsgProto.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientMsgProto::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:shm_ipc.ClientMsgProto.payload)
}
inline std::string* ClientMsgProto::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:shm_ipc.ClientMsgProto.payload)
  return _s;
}
inline const std::string& ClientMsgProto::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void ClientMsgProto::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* ClientMsgProto::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* ClientMsgProto::release_payload() {
  // @@protoc_insertion_point(field_release:shm_ipc.ClientMsgProto.payload)
  return _impl_.payload_.Release();
}
inline void ClientMsgProto::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:shm_ipc.ClientMsgProto.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace shm_ipc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_shm_5fmessages_2eproto
